# fly.toml app configuration file generated for battlesnakes-go-2025 on 2025-01-06T15:32:04-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'battlesnakes-go-2025'
primary_region = 'sea'

[build]
  [build.args]
    GO_VERSION = '1.21.6'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
